### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by mitmelon** [ac12644/Blockchain#1]
If I want to use this in production to create a coin just exactly like Bitcoin... How do I go about it please

**Comment by ac12644** [comment]
Hi! I got your point. So, when you add a new block this means you're creating a new coin. When you go to [chain.js](https://github.com/ac12644/Blockchain/blob/main/chain.js) line 58, you'll see:

`const generateNextBlock = (txns) => {
    const prevBlock = getLatestBlock(),
        prevMerkleRoot = prevBlock.blockHeader.merkleRoot;
    nextIndex = prevBlock.index + 1,
        nextTime = moment().unix(),
        nextMerkleRoot = CryptoJS.SHA256(1, prevMerkleRoot, nextTime).toString();

    const blockHeader = new BlockHeader(1, prevMerkleRoot, nextMerkleRoot, nextTime);
    const newBlock = new Block(blockHeader, nextIndex, txns);
    blockchain.push(newBlock);
    storeBlock(newBlock);
    return newBlock;
};`

In this block, you are passing 4 parameters { 1, prevMerkleRoot, nextMerkleRoot, nextTime } you can also add more parameters like the name of sender and recipient. This information is stored in a hash which we consider a coin which you can modify based on your needs.

**Comment by mitmelon** [comment]
> Hi! I got your point. So, when you add a new block this means you're creating a new coin. When you go to [chain.js](https://github.com/ac12644/Blockchain/blob/main/chain.js) line 58, you'll see:
> 
> `const generateNextBlock = (txns) => { const prevBlock = getLatestBlock(), prevMerkleRoot = prevBlock.blockHeader.merkleRoot; nextIndex = prevBlock.index + 1, nextTime = moment().unix(), nextMerkleRoot = CryptoJS.SHA256(1, prevMerkleRoot, nextTime).toString();
> 
> ```
> const blockHeader = new BlockHeader(1, prevMerkleRoot, nextMerkleRoot, nextTime);
> const newBlock = new Block(blockHeader, nextIndex, txns);
> blockchain.push(newBlock);
> storeBlock(newBlock);
> return newBlock;
> ```
> 
> };`
> 
> In this block, you are passing 4 parameters { 1, prevMerkleRoot, nextMerkleRoot, nextTime } you can also add more parameters like the name of sender and recipient. This information is stored in a hash which we consider a coin which you can modify based on your needs.

I get it now... But can I use this code on production server... To create a coin and allow miners to mine transactions...

I mean is this code secure to start my own coin creation like Bitcoin?

**Comment by ac12644** [comment]
yes
